name: SignCodePad
main: de.davboecki.signcodepad.SignCodePad
version: 2.0.2
website: http://dev.bukkit.org/server-mods/signcodepad/
dev-url: http://dev.bukkit.org/server-mods/signcodepad/

permissions:
  signcodepad.*:
    description: All commands
    children:
      signcodepad.masterdestroy: true
      signcodepad.replaceblock: true
      signcodepad.use: true
      signcodepad.create: true
  signcodepad.masterdestroy:
    default: op
  signcodepad.replaceblock:
    default: op
  signcodepad.use:
    default: false
  signcodepad.create:
    default: false