name: SignCodePad
main: de.davboecki.signcodepad.SignCodePad
version: 2.3.0
website: http://dev.bukkit.org/server-mods/signcodepad/
dev-url: http://dev.bukkit.org/server-mods/signcodepad/
# api-version: 1.18 # ToDo: Not wall torch when using api-version.

permissions:
  signcodepad.*:
    description: All commands
    children:
      signcodepad.masterdestroy: true
      signcodepad.replaceblock: true
      signcodepad.use: true
      signcodepad.create: true
  signcodepad.masterdestroy:
    default: op
  signcodepad.replaceblock:
    default: op
  signcodepad.use:
    default: false
  signcodepad.create:
    default: false
  signcodepad.disablejoinmessage:
    default: false